In [1]:
import pandas as pd
import numpy as np

In [2]:
slum = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\emilybroh_capstone\data\Removed\slums_norm_withbothpts_onlycountries.csv")

In [3]:
slum

,country,year,pct_slums,norm_pct_slums,norm_with_pts,norm_log5
0,Germany,2017.0,0.000000,1.000000,5.000000,32.000000
1,Denmark,2017.0,0.000000,1.000000,5.000000,32.000000
2,Finland,2017.0,0.000000,1.000000,5.000000,32.000000
3,France,2017.0,0.000000,1.000000,5.000000,32.000000
4,Belgium,2017.0,0.000000,1.000000,5.000000,32.000000
...,...,...,...,...,...,...
199,Afghanistan,2017.0,71.210000,0.244055,1.220276,7.809766
200,Sudan,2017.0,76.223333,0.190835,0.954176,6.106723
201,Democratic Republic of Congo,2017.0,77.133333,0.181175,0.905874,5.797594
202,Chad,2017.0,82.846667,0.120524,0.602619,3.856759
203,South Sudan,2017.0,94.200000,0.000000,0.000000,0.000000

In [4]:
elec = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\electric_with_allpts_onlycountries.csv")

In [29]:
hap = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\emilybroh_capstone\data\Category_D_E\happiness_20202024.csv")

In [35]:
gdp = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\emilybroh_capstone\data\Category_Misc\GDP_0417.csv")

In [37]:
r = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\emilybroh_capstone\data\Category_D_E\renew_20182022.csv")

In [39]:
r_corr = r[['country_c', 'renew']]

In [41]:
gdp_corr = gdp[['country_c', 'gdp']]

In [43]:
gr_corr = pd.merge(r_corr, gdp_corr, on = 'country_c', how = 'inner')

In [45]:
gr_corr = gr_corr[['renew', 'gdp']]

In [47]:
elec_corr = elec[['country', 'access_electricity']]

In [49]:
gre_corr = pd.merge(gdp_corr, elec, left_on = 'country_c', right_on = 'country',  how = 'inner')

In [51]:
gre_corr = pd.merge(gre_corr, r_corr, left_on = 'country', right_on = 'country_c',  how = 'inner')

In [53]:
gre_corr2 = gre_corr[['gdp', 'access_electricity', 'renew']]

In [55]:
gre_corr2.corr()

                         gdp  access_electricity     renew
gdp                 1.000000            0.514504 -0.074217
access_electricity  0.514504            1.000000 -0.196599
renew              -0.074217           -0.196599  1.000000

In [57]:
greh = pd.merge(gre_corr, hap, on = 'country', how = 'inner')

In [59]:
greh2 = greh[['gdp',  'access_electricity',
      'renew', 'happiness']]

In [61]:
greh_corr = greh2.corr()
type(greh_corr)

pandas.core.frame.DataFrame

In [63]:
greh.describe()

,gdp,year_x,access_electricity,norm_access_electricity,norm_with_pts,norm_pts_log5,renew,year_y,happiness,norm_hap,happiness_log4_n
count,145.00000,145.0,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000
mean,26111.19847,2017.0,84.397806,0.834627,4.173135,26.708063,39.274241,2021.982759,5.528409,0.611256,2.445024
std,25445.03219,0.0,25.847816,0.273970,1.369850,8.767037,31.718248,0.490938,1.123270,0.193181,0.772724
min,836.91335,2017.0,8.636364,0.031605,0.158027,1.011370,0.000000,2020.000000,1.974200,0.000000,0.000000
25%,6178.23060,2017.0,78.854545,0.775872,3.879360,24.827905,12.219025,2022.000000,4.681400,0.465587,1.862347
50%,16488.52040,2017.0,99.645455,0.996242,4.981210,31.879746,29.817098,2022.000000,5.727200,0.645444,2.581777
75%,39870.70540,2017.0,100.000000,1.000000,5.000000,32.000000,64.668641,2022.000000,6.332800,0.749596,2.998383
max,134529.65000,2017.0,100.000000,1.000000,5.000000,32.000000,100.000000,2024.000000,7.788800,1.000000,4.000000

In [64]:
greh.to_csv('Greh_corr_0417.csv', index=False, header=True)

In [67]:
un = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\emilybroh_capstone\data\Category_B\unemploy_20192023.csv")

In [69]:
crime = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\emilybroh_capstone\data\Category_B\Crime_2024.csv")

In [71]:
un2 = un[['country_c', 'unem']]

In [73]:
crime2 = crime[['country_c', 'crime_rate']]

In [75]:
uc = pd.merge(un2, crime, on = 'country_c',  how = 'inner')

In [87]:
greh = greh[['country', 'gdp', 'access_electricity',
       'norm_access_electricity','renew', 'happiness']]

In [91]:
grehuc = pd.merge(greh, uc, on = 'country', how = 'inner')

In [79]:
grehuc2 = grehuc[[ 'gdp', 'access_electricity',
    'renew',  'happiness', 'unem','crime_rate']]

NameError: name 'grehuc' is not defined

In [99]:
grehuc = grehuc[['country', 'gdp', 'access_electricity', 
       'renew', 'happiness', 'country_c', 'unem', 'crime_rate']]

In [101]:
func = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\emilybroh_capstone\data\Category_B\func_gov_20192023.csv")

In [103]:
atk = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\emilybroh_capstone\data\Category_B\atk_20202021.csv")

In [17]:
# cat_abcd.corr(numeric_only=True)

In [105]:
atk2 = atk[['country_c', 'ineq']]

In [107]:
func2 = func[['country_c', 'gov']]
type(atk2)

pandas.core.frame.DataFrame

In [109]:
grehuca = pd.merge(grehuc, atk2, on = 'country_c', how = 'inner')

In [113]:
grehucaf =  pd.merge(grehuca, func2, on = 'country_c', how = 'inner')
grehucaf2 =  pd.merge(grehuca, func2, on = 'country_c', how = 'inner')
grehucaf =grehucaf[[ 'gdp', 'access_electricity',
        'renew',  'happiness', 
        'unem','crime_rate',
        'ineq', 'gov']]

In [115]:
grehucaf_corr = grehucaf.corr(numeric_only = True)

In [117]:
grehucaf_corr.to_csv('Grehucaf_corr_0418.csv', index=False, header=True)

In [119]:
gdp.describe()
quartiles = gdp['gdp'].quantile([0.25, 0.5, 0.75])

gdp_25 = gdp['gdp'].quantile(0.25)
gdp_75 = gdp['gdp'].quantile(0.75)

In [121]:
lgbt = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\emilybroh_capstone\data\Category_C\lgbt_2025.csv")

In [123]:
s = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\emilybroh_capstone\data\Category_C\suicide_2019.csv")

In [125]:
grehucaf.corr(method = 'spearman')

,gdp,access_electricity,renew,happiness,unem,crime_rate,ineq,gov
gdp,1.000000,0.885469,-0.085821,0.849496,-0.137854,-0.540285,-0.696946,0.735510
access_electricity,0.885469,1.000000,-0.156178,0.734860,-0.052034,-0.621493,-0.778425,0.578909
renew,-0.085821,-0.156178,1.000000,0.163654,0.047608,0.132183,0.207001,0.152089
happiness,0.849496,0.734860,0.163654,1.000000,-0.242360,-0.346325,-0.555810,0.716706
unem,-0.137854,-0.052034,0.047608,-0.242360,1.000000,0.151835,0.168650,-0.068271
crime_rate,-0.540285,-0.621493,0.132183,-0.346325,0.151835,1.000000,0.571573,-0.318833
ineq,-0.696946,-0.778425,0.207001,-0.555810,0.168650,0.571573,1.000000,-0.367239
gov,0.735510,0.578909,0.152089,0.716706,-0.068271,-0.318833,-0.367239,1.000000

In [127]:
grehucaf.corr()

,gdp,access_electricity,renew,happiness,unem,crime_rate,ineq,gov
gdp,1.000000,0.447635,-0.019517,0.722319,-0.246056,-0.509057,-0.545730,0.655832
access_electricity,0.447635,1.000000,-0.279353,0.590733,-0.030809,-0.368683,-0.688904,0.379654
renew,-0.019517,-0.279353,1.000000,0.094117,-0.023603,0.136517,0.258960,0.134390
happiness,0.722319,0.590733,0.094117,1.000000,-0.343854,-0.383963,-0.548857,0.689131
unem,-0.246056,-0.030809,-0.023603,-0.343854,1.000000,0.216181,0.284365,-0.175299
crime_rate,-0.509057,-0.368683,0.136517,-0.383963,0.216181,1.000000,0.570560,-0.341848
ineq,-0.545730,-0.688904,0.258960,-0.548857,0.284365,0.570560,1.000000,-0.325678
gov,0.655832,0.379654,0.134390,0.689131,-0.175299,-0.341848,-0.325678,1.000000

In [129]:
gdp_25 = gdp['gdp'].quantile(0.25)
gdp_25

6074.87325

In [131]:
gdp_25_75 = gdp[(gdp['gdp'] <= gdp_25) | (gdp['gdp'] >= gdp_75)]

#gdp_25 = gdp[(gdp['gdp'] >= gdp_25) & (gdp['gdp'] <= gdp_75)]

In [133]:
gdp_25_75 = gdp_25_75[['country_c', 'gdp']]

In [135]:
gdp_25_75.columns = ['country_c', 'gdp2575']

In [137]:
gdp_25_75

                    country_c       gdp2575
0                  Luxembourg  134529.65000
1                   Singapore  125350.60300
2                       Qatar  112790.94580
3                     Ireland  111456.13200
4                     Bermuda   94205.03980
..                        ...           ...
194                Mozambique    1488.11044
195                   Somalia    1413.98182
196                  DR Congo    1345.89978
197  Central African Republic    1136.54042
198                   Burundi     836.91335

[100 rows x 2 columns]

In [139]:
gdp_grehucaf = pd.merge(gdp_25_75, grehucaf2, on = 'country_c', how = 'inner')
gdp_grehucaf.columns

Index(['country_c', 'gdp2575', 'country', 'gdp', 'access_electricity', 'renew',
       'happiness', 'unem', 'crime_rate', 'ineq', 'gov'],
      dtype='object')

In [141]:
gdp_grehucaf = gdp_grehucaf[['country_c', 'gdp2575','access_electricity', 'renew', 'happiness','unem', 'crime_rate','ineq', 'gov']]

In [143]:
gdp_grehucaf.corr(numeric_only = True)

,gdp2575,access_electricity,renew,happiness,unem,crime_rate,ineq,gov
gdp2575,1.000000,0.702549,-0.188910,0.803795,-0.294577,-0.535099,-0.660778,0.760342
access_electricity,0.702549,1.000000,-0.333304,0.772971,-0.035872,-0.560817,-0.851852,0.677272
renew,-0.188910,-0.333304,1.000000,-0.159066,-0.010899,0.196715,0.287731,-0.062086
happiness,0.803795,0.772971,-0.159066,1.000000,-0.341357,-0.604732,-0.756981,0.862580
unem,-0.294577,-0.035872,-0.010899,-0.341357,1.000000,0.206934,0.246531,-0.403692
crime_rate,-0.535099,-0.560817,0.196715,-0.604732,0.206934,1.000000,0.575398,-0.606754
ineq,-0.660778,-0.851852,0.287731,-0.756981,0.246531,0.575398,1.000000,-0.707108
gov,0.760342,0.677272,-0.062086,0.862580,-0.403692,-0.606754,-0.707108,1.000000

In [145]:
gdp_grehucaf.corr(numeric_only = True, method = 'spearman')

,gdp2575,access_electricity,renew,happiness,unem,crime_rate,ineq,gov
gdp2575,1.000000,0.817567,-0.194648,0.863265,-0.127245,-0.492053,-0.699592,0.780315
access_electricity,0.817567,1.000000,-0.325419,0.800428,-0.049093,-0.603275,-0.775085,0.768778
renew,-0.194648,-0.325419,1.000000,0.006786,0.154035,0.250344,0.196383,0.031585
happiness,0.863265,0.800428,0.006786,1.000000,-0.085408,-0.457303,-0.708673,0.874761
unem,-0.127245,-0.049093,0.154035,-0.085408,1.000000,0.167266,0.190714,-0.097558
crime_rate,-0.492053,-0.603275,0.250344,-0.457303,0.167266,1.000000,0.572675,-0.501123
ineq,-0.699592,-0.775085,0.196383,-0.708673,0.190714,0.572675,1.000000,-0.673113
gov,0.780315,0.768778,0.031585,0.874761,-0.097558,-0.501123,-0.673113,1.000000

In [151]:
hdi = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\emilybroh_capstone\data\Category_D_E\hdi_withpts_onlycountries.csv")

In [153]:
grehucaf.corr()

,gdp,access_electricity,renew,happiness,unem,crime_rate,ineq,gov
gdp,1.000000,0.447635,-0.019517,0.722319,-0.246056,-0.509057,-0.545730,0.655832
access_electricity,0.447635,1.000000,-0.279353,0.590733,-0.030809,-0.368683,-0.688904,0.379654
renew,-0.019517,-0.279353,1.000000,0.094117,-0.023603,0.136517,0.258960,0.134390
happiness,0.722319,0.590733,0.094117,1.000000,-0.343854,-0.383963,-0.548857,0.689131
unem,-0.246056,-0.030809,-0.023603,-0.343854,1.000000,0.216181,0.284365,-0.175299
crime_rate,-0.509057,-0.368683,0.136517,-0.383963,0.216181,1.000000,0.570560,-0.341848
ineq,-0.545730,-0.688904,0.258960,-0.548857,0.284365,0.570560,1.000000,-0.325678
gov,0.655832,0.379654,0.134390,0.689131,-0.175299,-0.341848,-0.325678,1.000000

In [155]:
mat = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\emilybroh_capstone\data\Removed\maternal_mortality_withallpts_onlycountries.csv")

In [157]:
mat2 = mat[['country', 'maternal_mortality']]

In [159]:
grehucafm = pd.merge(grehucaf2, mat, left_on = 'country_c', right_on = 'country', how = 'inner')

In [161]:
grehucafm = grehucafm[['country_c', 'gdp', 'access_electricity',
       
        'renew',  'happiness', 
       'unem',  'crime_rate',
        'ineq', 'gov',
     'maternal_mortality']]

In [163]:
grehucafm.corr(numeric_only = True)

,gdp,access_electricity,renew,happiness,unem,crime_rate,ineq,gov,maternal_mortality
gdp,1.000000,0.447635,-0.019517,0.722319,-0.246056,-0.509057,-0.545730,0.655832,-0.465997
access_electricity,0.447635,1.000000,-0.279353,0.590733,-0.030809,-0.368683,-0.688904,0.379654,-0.703472
renew,-0.019517,-0.279353,1.000000,0.094117,-0.023603,0.136517,0.258960,0.134390,0.185456
happiness,0.722319,0.590733,0.094117,1.000000,-0.343854,-0.383963,-0.548857,0.689131,-0.600843
unem,-0.246056,-0.030809,-0.023603,-0.343854,1.000000,0.216181,0.284365,-0.175299,0.041460
crime_rate,-0.509057,-0.368683,0.136517,-0.383963,0.216181,1.000000,0.570560,-0.341848,0.483069
ineq,-0.545730,-0.688904,0.258960,-0.548857,0.284365,0.570560,1.000000,-0.325678,0.475928
gov,0.655832,0.379654,0.134390,0.689131,-0.175299,-0.341848,-0.325678,1.000000,-0.402442
maternal_mortality,-0.465997,-0.703472,0.185456,-0.600843,0.041460,0.483069,0.475928,-0.402442,1.000000

In [228]:
gni = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\emilybroh_capstone\data\Removed\gni_withallpts_onlycountries.csv")

In [230]:
gni2 = gni[['country', 'gni']]

In [232]:
int = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\emilybroh_capstone\data\Removed\internet_withpts_onlycountries.csv")

In [234]:
food = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\emilybroh_capstone\data\Removed\food_insecure_withpts_onlycountries0415.csv")

In [236]:
food

,country,year,modtosev_food_insecure_pct,norm_pct_foodinsecure,norm_withpts,norm_withpts_log5,foodinsecure_log32_n,country_c
0,Italy,2021.500000,0.000000,1.000000,5.000000,32.000000,32.000000,Italy
1,Kazakhstan,2019.500000,0.003769,0.996231,4.981155,31.879389,31.879389,Kazakhstan
2,Switzerland,2018.500000,0.009968,0.990032,4.950159,31.681016,31.681016,Switzerland
3,Luxembourg,2018.500000,0.014432,0.985568,4.927842,31.538187,31.538187,Luxembourg
4,Japan,2018.500000,0.017854,0.982146,4.910732,31.428685,31.428685,Japan
...,...,...,...,...,...,...,...,...
148,Malawi,2018.500000,0.929726,0.070274,0.351369,2.248760,2.248760,Malawi
149,Liberia,2018.571429,0.935359,0.064641,0.323207,2.068524,2.068524,Liberia
150,Haiti,2020.500000,0.958738,0.041262,0.206308,1.320373,1.320373,Haiti
151,Sierra Leone,2018.500000,0.976443,0.023557,0.117784,0.753819,0.753819,Sierra Leone
152,South Sudan,2019.500000,1.000000,0.000000,0.000000,0.000000,0.000000,South Sudan

In [238]:
slum = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\emilybroh_capstone\data\Removed\slums_norm_withbothpts_onlycountries.csv")

In [240]:
child = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\emilybroh_capstone\data\Removed\child_mortality_norm_withallpts_onlycountries.csv")

In [242]:
#grehucafm

grehucafms = pd.merge(grehucafm, slum, left_on = 'country_c', right_on = 'country', how = 'inner')

In [244]:
grehucafms = grehucafms[['country_c', 'gdp', 'access_electricity', 'renew', 'happiness', 'unem',
       'crime_rate', 'ineq', 'gov', 'maternal_mortality', 
       'pct_slums']]

In [246]:
grehucafmsc = pd.merge(grehucafms, child, left_on = 'country_c', right_on = 'country', how = 'inner')

In [248]:
grehucaffmsc = pd.merge(grehucafmsc, food, left_on = 'country_c', right_on = 'country', how = 'inner')

In [250]:
grehucaffmsc

,country_c_x,gdp,access_electricity,renew,happiness,unem,crime_rate,ineq,gov,maternal_mortality,...,norm_with_pts,norm_pts_log5,country_y,year_y,modtosev_food_insecure_pct,norm_pct_foodinsecure,norm_withpts,norm_withpts_log5,foodinsecure_log32_n,country_c_y
0,Luxembourg,134529.65000,100.000000,78.237780,7.2400,5.4776,34.4,0.173507,8.870000,7.070532,...,4.981149,31.879353,Luxembourg,2018.5,0.014432,0.985568,4.927842,31.538187,31.538187,Luxembourg
1,Singapore,125350.60300,100.000000,3.081360,6.5064,3.7806,23.5,0.259351,7.678333,7.347188,...,5.000000,32.000000,Singapore,2018.5,0.031690,0.968310,4.841549,30.985915,30.985915,Singapore
2,Ireland,111456.13200,100.000000,37.805935,6.9528,5.1172,46.5,0.139949,8.035000,6.098670,...,4.941530,31.625791,Ireland,2018.5,0.055793,0.944207,4.721037,30.214640,30.214640,Ireland
3,Norway,89001.77000,100.000000,98.489598,7.3272,3.8584,32.6,0.134010,9.640000,2.648812,...,4.972842,31.826187,Norway,2018.5,0.034219,0.965781,4.828903,30.904979,30.904979,Norway
4,Switzerland,81101.41200,100.000000,61.217775,7.2636,4.5316,25.3,0.174857,9.110000,7.285693,...,4.928110,31.539907,Switzerland,2018.5,0.009968,0.990032,4.950159,31.681016,31.681016,Switzerland
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,Zimbabwe,3246.44688,43.727273,60.725946,3.2162,8.8760,60.9,0.513789,2.500000,447.897476,...,2.892837,18.514154,Zimbabwe,2018.5,0.796568,0.203432,1.017159,6.509819,6.509819,Zimbabwe
91,Haiti,3150.02492,43.045455,14.719483,3.6150,14.8576,77.9,0.520696,0.678333,379.972499,...,2.049013,13.113681,Haiti,2020.5,0.958738,0.041262,0.206308,1.320373,1.320373,Haiti
92,Uganda,2713.66026,31.818182,97.653362,4.5008,3.2564,55.0,0.435286,3.450000,318.933335,...,2.464055,15.769953,Uganda,2018.5,0.837334,0.162666,0.813331,5.205316,5.205316,Uganda
93,Ethiopia,2590.79340,41.481818,99.948256,4.0732,3.5788,50.8,0.364550,3.213333,427.519322,...,2.574286,16.475430,Ethiopia,2018.5,0.661476,0.338524,1.692621,10.832771,10.832771,Ethiopia
94,Afghanistan,2363.04638,87.754545,83.951650,1.9742,12.6708,78.3,0.292251,0.248333,759.756665,...,2.727331,17.454917,Afghanistan,2018.5,0.718607,0.281393,1.406963,9.004563,9.004563,Afghanistan

In [252]:
grehucaffmsci = pd.merge(grehucaffmsc, int, left_on = 'country_c_x', right_on = 'country', how = 'inner')

In [256]:
grehucaffmsci = pd.merge(grehucaffmsci, gni2, left_on = 'country', right_on = 'country', how = 'inner')

In [258]:
grehucaffmsci.columns

Index(['country_c_x', 'gdp', 'access_electricity', 'renew', 'happiness',
       'unem', 'crime_rate', 'ineq', 'gov', 'maternal_mortality', 'pct_slums',
       'country_x', 'year_x', 'under_5yo_deaths', 'norm_deaths_pct',
       'norm_with_pts', 'norm_pts_log5', 'country_y', 'year_y',
       'modtosev_food_insecure_pct', 'norm_pct_foodinsecure', 'norm_withpts',
       'norm_withpts_log5', 'foodinsecure_log32_n', 'country_c_y', 'index',
       'country', 'year', 'internet', 'norm_internet', 'norm_internet_log8',
       'gni'],
      dtype='object')

In [278]:
grehucaffmsci = grehucaffmsci[['country', 'gdp', 'access_electricity', 'renew', 'happiness',
       'unem', 'crime_rate', 'ineq', 'gov', 'maternal_mortality', 'pct_slums','under_5yo_deaths', 'modtosev_food_insecure_pct',
        'index','internet','gni']]

In [280]:
grehucaffmsci.corr(numeric_only = True)

,gdp,access_electricity,renew,happiness,unem,crime_rate,ineq,gov,maternal_mortality,pct_slums,under_5yo_deaths,modtosev_food_insecure_pct,index,internet,gni
gdp,1.000000,0.445928,0.008134,0.718171,-0.240605,-0.542511,-0.533928,0.668972,-0.466614,-0.590937,-0.592442,-0.651259,-0.769229,0.792064,0.982016
access_electricity,0.445928,1.000000,-0.216294,0.605237,-0.047336,-0.435962,-0.634480,0.397115,-0.749963,-0.671935,-0.830403,-0.771459,-0.687871,0.595670,0.472819
renew,0.008134,-0.216294,1.000000,0.123694,-0.024685,0.101691,0.198927,0.131272,0.178432,0.136593,0.082991,0.186037,0.054476,-0.005850,-0.002418
happiness,0.718171,0.605237,0.123694,1.000000,-0.322743,-0.452851,-0.541343,0.753441,-0.612468,-0.690227,-0.690916,-0.695771,-0.803606,0.778265,0.751614
unem,-0.240605,-0.047336,-0.024685,-0.322743,1.000000,0.265392,0.352437,-0.182697,0.039389,0.044297,0.077994,0.158343,0.170455,-0.200102,-0.247131
crime_rate,-0.542511,-0.435962,0.101691,-0.452851,0.265392,1.000000,0.662596,-0.387469,0.508054,0.541423,0.549916,0.659820,0.619225,-0.612559,-0.578811
ineq,-0.533928,-0.634480,0.198927,-0.541343,0.352437,0.662596,1.000000,-0.323246,0.478951,0.613209,0.612131,0.701005,0.685861,-0.684029,-0.564424
gov,0.668972,0.397115,0.131272,0.753441,-0.182697,-0.387469,-0.323246,1.000000,-0.443434,-0.519673,-0.549258,-0.591810,-0.706627,0.710901,0.699458
maternal_mortality,-0.466614,-0.749963,0.178432,-0.612468,0.039389,0.508054,0.478951,-0.443434,1.000000,0.689898,0.904951,0.704720,0.729633,-0.611638,-0.494253
pct_slums,-0.590937,-0.671935,0.136593,-0.690227,0.044297,0.541423,0.613209,-0.519673,0.689898,1.000000,0.778402,0.732290,0.824479,-0.777443,-0.628048
under_5yo_deaths,-0.592442,-0.830403,0.082991,-0.690916,0.077994,0.549916,0.612131,-0.549258,0.904951,0.778402,1.000000,0.775511,0.840355,-0.747316,-0.625881
modtosev_food_insecure_pct,-0.651259,-0.771459,0.186037,-0.695771,0.158343,0.659820,0.701005,-0.591810,0.704720,0.732290,0.775511,1.000000,0.805321,-0.758591,-0.683784
index,-0.769229,-0.687871,0.054476,-0.803606,0.170455,0.619225,0.685861,-0.706627,0.729633,0.824479,0.840355,0.805321,1.000000,-0.979334,-0.816617
internet,0.792064,0.595670,-0.005850,0.778265,-0.200102,-0.612559,-0.684029,0.710901,-0.611638,-0.777443,-0.747316,-0.758591,-0.979334,1.000000,0.843360
gni,0.982016,0.472819,-0.002418,0.751614,-0.247131,-0.578811,-0.564424,0.699458,-0.494253,-0.628048,-0.625881,-0.683784,-0.816617,0.843360,1.000000

In [282]:
grehucaffmsci.corr(numeric_only = True, method = 'spearman')

,gdp,access_electricity,renew,happiness,unem,crime_rate,ineq,gov,maternal_mortality,pct_slums,under_5yo_deaths,modtosev_food_insecure_pct,index,internet,gni
gdp,1.000000,0.888283,-0.034995,0.858315,-0.115244,-0.592989,-0.672550,0.768630,-0.869093,-0.838733,-0.906172,-0.828530,-0.921431,0.921431,0.998642
access_electricity,0.888283,1.000000,-0.106611,0.758126,-0.036612,-0.665240,-0.775155,0.608487,-0.886959,-0.830654,-0.885989,-0.803295,-0.881599,0.881599,0.891589
renew,-0.034995,-0.106611,1.000000,0.197805,0.037347,0.100873,0.154509,0.155271,0.071977,-0.016594,-0.034127,0.108785,-0.015692,0.015692,-0.039950
happiness,0.858315,0.758126,0.197805,1.000000,-0.203541,-0.413090,-0.557741,0.763101,-0.738004,-0.781598,-0.800279,-0.697609,-0.822900,0.822900,0.855389
unem,-0.115244,-0.036612,0.037347,-0.203541,1.000000,0.200414,0.162486,-0.075031,0.047312,0.022316,0.067582,0.181601,0.083875,-0.083875,-0.112388
crime_rate,-0.592989,-0.665240,0.100873,-0.413090,0.200414,1.000000,0.662113,-0.366002,0.677077,0.557257,0.662355,0.648274,0.591533,-0.591533,-0.597069
ineq,-0.672550,-0.775155,0.154509,-0.557741,0.162486,0.662113,1.000000,-0.375986,0.727156,0.685238,0.678791,0.694571,0.707167,-0.707167,-0.674594
gov,0.768630,0.608487,0.155271,0.763101,-0.075031,-0.366002,-0.375986,1.000000,-0.645648,-0.656073,-0.743799,-0.639379,-0.745316,0.745316,0.765039
maternal_mortality,-0.869093,-0.886959,0.071977,-0.738004,0.047312,0.677077,0.727156,-0.645648,1.000000,0.861344,0.918295,0.786768,0.876428,-0.876428,-0.870507
pct_slums,-0.838733,-0.830654,-0.016594,-0.781598,0.022316,0.557257,0.685238,-0.656073,0.861344,1.000000,0.843142,0.721933,0.876712,-0.876712,-0.837333
under_5yo_deaths,-0.906172,-0.885989,-0.034127,-0.800279,0.067582,0.662355,0.678791,-0.743799,0.918295,0.843142,1.000000,0.799840,0.899187,-0.899187,-0.909609
modtosev_food_insecure_pct,-0.828530,-0.803295,0.108785,-0.697609,0.181601,0.648274,0.694571,-0.639379,0.786768,0.721933,0.799840,1.000000,0.787034,-0.787034,-0.827075
index,-0.921431,-0.881599,-0.015692,-0.822900,0.083875,0.591533,0.707167,-0.745316,0.876428,0.876712,0.899187,0.787034,1.000000,-1.000000,-0.923390
internet,0.921431,0.881599,0.015692,0.822900,-0.083875,-0.591533,-0.707167,0.745316,-0.876428,-0.876712,-0.899187,-0.787034,-1.000000,1.000000,0.923390
gni,0.998642,0.891589,-0.039950,0.855389,-0.112388,-0.597069,-0.674594,0.765039,-0.870507,-0.837333,-0.909609,-0.827075,-0.923390,0.923390,1.000000

In [284]:
hom = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\emilybroh_capstone\data\Removed\homicide_withallpts_onlycountries.csv")

In [286]:
hom2 = hom[['country', 'homicide_rate']]

In [288]:
grehhucaffmsci = pd.merge(grehucafms, hom2, left_on = 'country_c', right_on = 'country', how = 'inner')

In [290]:
grehhucaffmsci = pd.merge(grehhucaffmsci, child, left_on = 'country_c', right_on = 'country', how = 'inner')

In [292]:
grehhucaffmsci.columns

Index(['country_c', 'gdp', 'access_electricity', 'renew', 'happiness', 'unem',
       'crime_rate', 'ineq', 'gov', 'maternal_mortality', 'pct_slums',
       'country_x', 'homicide_rate', 'country_y', 'year', 'under_5yo_deaths',
       'norm_deaths_pct', 'norm_with_pts', 'norm_pts_log5'],
      dtype='object')

In [294]:
grehhucaffmsci = grehhucaffmsci[['country_c', 'gdp', 'access_electricity', 'renew', 'happiness', 'unem',
       'crime_rate', 'ineq', 'gov', 'maternal_mortality', 'pct_slums',
        'homicide_rate', 'under_5yo_deaths']]

In [296]:
grehhucaffmsci.corr(numeric_only = True)

,gdp,access_electricity,renew,happiness,unem,crime_rate,ineq,gov,maternal_mortality,pct_slums,homicide_rate,under_5yo_deaths
gdp,1.000000,0.452466,-0.008908,0.718752,-0.246329,-0.517215,-0.545007,0.661886,-0.465481,-0.599763,-0.320154,-0.599067
access_electricity,0.452466,1.000000,-0.289548,0.593952,-0.031342,-0.371671,-0.688130,0.375566,-0.705816,-0.662096,-0.107676,-0.836772
renew,-0.008908,-0.289548,1.000000,0.107457,-0.048130,0.140942,0.266701,0.147733,0.201360,0.161335,0.149376,0.145163
happiness,0.718752,0.593952,0.107457,1.000000,-0.343460,-0.388960,-0.546934,0.691690,-0.602350,-0.687083,-0.048665,-0.687283
unem,-0.246329,-0.031342,-0.048130,-0.343460,1.000000,0.218876,0.287473,-0.170408,0.049004,0.060103,0.098543,0.065960
crime_rate,-0.517215,-0.371671,0.140942,-0.388960,0.218876,1.000000,0.578449,-0.348906,0.486710,0.510364,0.548853,0.519560
ineq,-0.545007,-0.688130,0.266701,-0.546934,0.287473,0.578449,1.000000,-0.317137,0.474391,0.637005,0.336187,0.657955
gov,0.661886,0.375566,0.147733,0.691690,-0.170408,-0.348906,-0.317137,1.000000,-0.406377,-0.491547,-0.150592,-0.513001
maternal_mortality,-0.465481,-0.705816,0.201360,-0.602350,0.049004,0.486710,0.474391,-0.406377,1.000000,0.676778,0.189960,0.878907
pct_slums,-0.599763,-0.662096,0.161335,-0.687083,0.060103,0.510364,0.637005,-0.491547,0.676778,1.000000,0.180035,0.791283
homicide_rate,-0.320154,-0.107676,0.149376,-0.048665,0.098543,0.548853,0.336187,-0.150592,0.189960,0.180035,1.000000,0.203786
under_5yo_deaths,-0.599067,-0.836772,0.145163,-0.687283,0.065960,0.519560,0.657955,-0.513001,0.878907,0.791283,0.203786,1.000000

In [298]:
urb = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\emilybroh_capstone\data\Category_Misc\share-of-population-urban (1)\share-of-population-urban.csv")

In [300]:
urb.columns = ['country', 'code', 'year', 'urb_pop']

In [302]:
urb = urb.loc[urb['year'] >= 2020]

In [304]:
urb = urb.groupby('country').mean('urb_pop').reset_index()

In [306]:
urb = urb[['country', 'urb_pop']]

In [308]:
grehhuucaffmsci = pd.merge(grehhucaffmsci, urb, left_on = 'country_c', right_on = 'country', how = 'inner')

In [316]:
grehhuucaffmsci = grehhuucaffmsci[['country_c', 'gdp', 'access_electricity', 'renew', 'happiness', 'unem',
       'crime_rate', 'ineq', 'gov', 'maternal_mortality', 'pct_slums',
       'homicide_rate', 'under_5yo_deaths',  'urb_pop']]

In [629]:
fifteen_varcorr = grehhuucaffmsci.corr(numeric_only = True)

In [633]:
fifteen_varcorr.to_csv('fifteen_varcorr_0418.csv', index=False, header=True)

In [322]:
life = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\EmilyBroh_Capstone\emilybroh_capstone\data\Category_A\LifeExpect_2018.csv")

In [404]:
grehhuucaffmscil = pd.merge(grehhucaffmsci, life, left_on = 'country_c', right_on = 'country', how = 'inner')

In [326]:
grehhuucaffmscil.to_csv('sixteen_varcorr_0418.csv', index=False, header=True)

In [408]:
grehhuucaffmscil = grehhuucaffmscil[['country', 'gdp', 'access_electricity', 'renew', 'happiness',
       'unem', 'crime_rate', 'ineq', 'gov', 'maternal_mortality', 'pct_slums',
       'homicide_rate', 'under_5yo_deaths', 'avg_life']]
grehhuucaffmscil

,country,gdp,access_electricity,renew,happiness,unem,crime_rate,ineq,gov,maternal_mortality,pct_slums,homicide_rate,under_5yo_deaths,avg_life
0,Luxembourg,134529.65000,100.000000,78.237780,7.2400,5.4776,34.4,0.173507,8.870000,7.070532,0.016667,0.714644,0.270000,81.53
1,Singapore,125350.60300,100.000000,3.081360,6.5064,3.7806,23.5,0.259351,7.678333,7.347188,23.608333,0.268110,0.216364,83.15
2,Ireland,111456.13200,100.000000,37.805935,6.9528,5.1172,46.5,0.139949,8.035000,6.098670,8.250000,0.922686,0.382727,81.91
3,Norway,89001.77000,100.000000,98.489598,7.3272,3.8584,32.6,0.134010,9.640000,2.648812,0.000000,0.722262,0.293636,82.64
4,Switzerland,81101.41200,100.000000,61.217775,7.2636,4.5316,25.3,0.174857,9.110000,7.285693,0.000000,0.595970,0.420909,83.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,Rwanda,2772.87118,33.445455,52.864568,3.3415,13.7750,26.8,0.443340,4.348333,310.214704,42.990000,3.027760,5.962727,66.29
103,Uganda,2713.66026,31.818182,97.653362,4.5008,3.2564,55.0,0.435286,3.450000,318.933335,58.271667,11.162656,7.431818,65.44
104,Ethiopia,2590.79340,41.481818,99.948256,4.0732,3.5788,50.8,0.364550,3.213333,427.519322,67.406667,8.631964,7.118182,64.92
105,Afghanistan,2363.04638,87.754545,83.951650,1.9742,12.6708,78.3,0.292251,0.248333,759.756665,71.210000,6.172616,6.682727,62.79
106,Mozambique,1488.11044,27.181818,82.002480,5.0404,3.7298,63.7,0.553966,1.548333,218.694043,60.815000,3.677822,9.011818,60.35

In [334]:
sixteen_pearsoncorr = grehhuucaffmscil.corr(numeric_only = True)

In [336]:
sixteen_spearmancorr = grehhuucaffmscil.corr(numeric_only = True, method = 'spearman')

In [338]:
sixteen_spearmancorr.to_csv('sixteen_spearmancorr0418.csv', index=False, header=True)

In [340]:
sixteen_pearsoncorr.to_csv('sixteen_pearsoncorr0418.csv', index=False, header=True)

In [342]:
sixteen_pearsoncorr

,gdp,access_electricity,renew,happiness,unem,crime_rate,ineq,gov,maternal_mortality,pct_slums,homicide_rate,under_5yo_deaths,avg_life
gdp,1.000000,0.452466,-0.008908,0.718752,-0.246329,-0.517215,-0.545007,0.661886,-0.465481,-0.599763,-0.320154,-0.599067,0.738730
access_electricity,0.452466,1.000000,-0.289548,0.593952,-0.031342,-0.371671,-0.688130,0.375566,-0.705816,-0.662096,-0.107676,-0.836772,0.744891
renew,-0.008908,-0.289548,1.000000,0.107457,-0.048130,0.140942,0.266701,0.147733,0.201360,0.161335,0.149376,0.145163,-0.104802
happiness,0.718752,0.593952,0.107457,1.000000,-0.343460,-0.388960,-0.546934,0.691690,-0.602350,-0.687083,-0.048665,-0.687283,0.742228
unem,-0.246329,-0.031342,-0.048130,-0.343460,1.000000,0.218876,0.287473,-0.170408,0.049004,0.060103,0.098543,0.065960,-0.149362
crime_rate,-0.517215,-0.371671,0.140942,-0.388960,0.218876,1.000000,0.578449,-0.348906,0.486710,0.510364,0.548853,0.519560,-0.565148
ineq,-0.545007,-0.688130,0.266701,-0.546934,0.287473,0.578449,1.000000,-0.317137,0.474391,0.637005,0.336187,0.657955,-0.652823
gov,0.661886,0.375566,0.147733,0.691690,-0.170408,-0.348906,-0.317137,1.000000,-0.406377,-0.491547,-0.150592,-0.513001,0.631843
maternal_mortality,-0.465481,-0.705816,0.201360,-0.602350,0.049004,0.486710,0.474391,-0.406377,1.000000,0.676778,0.189960,0.878907,-0.787399
pct_slums,-0.599763,-0.662096,0.161335,-0.687083,0.060103,0.510364,0.637005,-0.491547,0.676778,1.000000,0.180035,0.791283,-0.747212
homicide_rate,-0.320154,-0.107676,0.149376,-0.048665,0.098543,0.548853,0.336187,-0.150592,0.189960,0.180035,1.000000,0.203786,-0.327411
under_5yo_deaths,-0.599067,-0.836772,0.145163,-0.687283,0.065960,0.519560,0.657955,-0.513001,0.878907,0.791283,0.203786,1.000000,-0.892499
avg_life,0.738730,0.744891,-0.104802,0.742228,-0.149362,-0.565148,-0.652823,0.631843,-0.787399,-0.747212,-0.327411,-0.892499,1.000000

In [402]:
grehhuucaffmscil.to_csv('sixteen_varcorr_0418.csv', index=False, header=True)

In [354]:
trustgov = pd.read_csv(r"C:\Users\eabro\Downloads\share-who-trust-government\share-who-trust-government.csv")

In [358]:
trustgov.columns = ['country', 'code', 'year',
       'trust_nat_gov']

In [368]:
trustgov = trustgov.groupby('country').mean('trust_nat_gov')

In [382]:
trustgov = trustgov.sort_values('trust_nat_gov', ascending = False).reset_index()

In [384]:
trustgov.columns

Index(['country', 'year', 'trust_nat_gov'], dtype='object')

In [386]:
trustgov = trustgov[['country', 'trust_nat_gov']]

In [388]:
tgrehhuucaffmscil = pd.merge(grehhuucaffmscil, trustgov, on = 'country', how = 'inner')

In [410]:
tgrehhuucaffmscil

,country,gdp,access_electricity,renew,happiness,unem,crime_rate,ineq,gov,maternal_mortality,pct_slums,homicide_rate,under_5yo_deaths,avg_life,trust_nat_gov
0,Ireland,111456.13200,100.000000,37.805935,6.9528,5.1172,46.5,0.139949,8.035000,6.098670,8.250000,0.922686,0.382727,81.91,79.5
1,Norway,89001.77000,100.000000,98.489598,7.3272,3.8584,32.6,0.134010,9.640000,2.648812,0.000000,0.722262,0.293636,82.64,94.3
2,Switzerland,81101.41200,100.000000,61.217775,7.2636,4.5316,25.3,0.174857,9.110000,7.285693,0.000000,0.595970,0.420909,83.34,93.3
3,United States,71120.37820,100.000000,19.830755,6.8542,4.8696,49.3,0.256936,6.608333,17.610667,0.165000,4.849181,0.699091,78.38,52.5
4,Netherlands,69406.99000,100.000000,27.229993,7.3814,3.6988,26.3,0.126033,9.050000,5.228522,0.000000,0.746294,0.412727,81.67,78.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,Zambia,3548.96052,37.845455,87.139390,3.8458,5.7344,46.4,0.633985,3.345000,178.852044,50.846667,5.747617,6.664545,62.31,47.1
82,Tanzania,3519.06232,31.572727,35.272242,3.7200,2.6642,54.5,0.410997,5.060000,340.351007,51.425000,6.879821,6.990909,65.25,89.9
83,Zimbabwe,3246.44688,43.727273,60.725946,3.2162,8.8760,60.9,0.513789,2.500000,447.897476,28.111667,5.738526,6.211818,60.25,69.0
84,Uganda,2713.66026,31.818182,97.653362,4.5008,3.2564,55.0,0.435286,3.450000,318.933335,58.271667,11.162656,7.431818,65.44,46.9
85,Ethiopia,2590.79340,41.481818,99.948256,4.0732,3.5788,50.8,0.364550,3.213333,427.519322,67.406667,8.631964,7.118182,64.92,78.1

In [416]:
seventeen = tgrehhuucaffmscil 
seventeen

,country,gdp,access_electricity,renew,happiness,unem,crime_rate,ineq,gov,maternal_mortality,pct_slums,homicide_rate,under_5yo_deaths,avg_life,trust_nat_gov
0,Ireland,111456.13200,100.000000,37.805935,6.9528,5.1172,46.5,0.139949,8.035000,6.098670,8.250000,0.922686,0.382727,81.91,79.5
1,Norway,89001.77000,100.000000,98.489598,7.3272,3.8584,32.6,0.134010,9.640000,2.648812,0.000000,0.722262,0.293636,82.64,94.3
2,Switzerland,81101.41200,100.000000,61.217775,7.2636,4.5316,25.3,0.174857,9.110000,7.285693,0.000000,0.595970,0.420909,83.34,93.3
3,United States,71120.37820,100.000000,19.830755,6.8542,4.8696,49.3,0.256936,6.608333,17.610667,0.165000,4.849181,0.699091,78.38,52.5
4,Netherlands,69406.99000,100.000000,27.229993,7.3814,3.6988,26.3,0.126033,9.050000,5.228522,0.000000,0.746294,0.412727,81.67,78.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,Zambia,3548.96052,37.845455,87.139390,3.8458,5.7344,46.4,0.633985,3.345000,178.852044,50.846667,5.747617,6.664545,62.31,47.1
82,Tanzania,3519.06232,31.572727,35.272242,3.7200,2.6642,54.5,0.410997,5.060000,340.351007,51.425000,6.879821,6.990909,65.25,89.9
83,Zimbabwe,3246.44688,43.727273,60.725946,3.2162,8.8760,60.9,0.513789,2.500000,447.897476,28.111667,5.738526,6.211818,60.25,69.0
84,Uganda,2713.66026,31.818182,97.653362,4.5008,3.2564,55.0,0.435286,3.450000,318.933335,58.271667,11.162656,7.431818,65.44,46.9
85,Ethiopia,2590.79340,41.481818,99.948256,4.0732,3.5788,50.8,0.364550,3.213333,427.519322,67.406667,8.631964,7.118182,64.92,78.1

In [412]:
eighteen = pd.merge(int, seventeen, on = 'country', how = 'inner')
eighteen

,index,country,year,internet,norm_internet,norm_internet_log8,gdp,access_electricity,renew,happiness,unem,crime_rate,ineq,gov,maternal_mortality,pct_slums,homicide_rate,under_5yo_deaths,avg_life,trust_nat_gov
0,4,Switzerland,2020.0,46.962643,0.831132,6.649059,81101.41200,100.000000,61.217775,7.2636,4.5316,25.3,0.174857,9.110000,7.285693,0.000000,0.595970,0.420909,83.34,93.3
1,5,France,2020.0,46.323157,0.819815,6.558518,53983.22600,100.000000,21.977719,6.6480,7.7860,55.3,0.175082,7.680000,8.286672,0.000000,1.257723,0.397273,82.46,56.3
2,8,Denmark,2020.0,44.235214,0.782862,6.262899,69255.06000,100.000000,77.999250,7.5892,5.0548,26.3,0.110925,9.170000,5.453943,0.000000,0.976283,0.391818,81.12,79.3
3,9,South Korea,2020.0,43.393286,0.767962,6.143695,48497.68700,100.000000,6.228215,5.9654,3.3630,24.9,0.164216,8.213333,7.245308,4.350000,0.765223,0.357273,83.14,52.8
4,10,Norway,2019.5,43.303817,0.766378,6.131027,89001.77000,100.000000,98.489598,7.3272,3.8584,32.6,0.134010,9.640000,2.648812,0.000000,0.722262,0.293636,82.64,94.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,186,Zambia,2020.0,0.405331,0.007160,0.057280,3548.96052,37.845455,87.139390,3.8458,5.7344,46.4,0.633985,3.345000,178.852044,50.846667,5.747617,6.664545,62.31,47.1
82,188,Ghana,2020.0,0.351477,0.006207,0.049655,6610.83662,78.045455,37.831993,4.6388,3.1884,43.9,0.509502,5.178333,286.262974,35.170000,1.828209,6.594545,63.97,60.6
83,192,Ethiopia,2019.8,0.244803,0.004319,0.034552,2590.79340,41.481818,99.948256,4.0732,3.5788,50.8,0.364550,3.213333,427.519322,67.406667,8.631964,7.118182,64.92,78.1
84,206,Uganda,2021.0,0.082673,0.001450,0.011597,2713.66026,31.818182,97.653362,4.5008,3.2564,55.0,0.435286,3.450000,318.933335,58.271667,11.162656,7.431818,65.44,46.9
85,214,Nigeria,2020.0,0.040940,0.000711,0.005688,5535.29314,56.027273,22.960540,4.8116,4.6424,66.2,0.187159,3.810000,1108.942782,53.088333,27.672493,12.645455,52.82,23.1

In [398]:
eighteen.corr(numeric_only = True)

,index,year,internet,norm_internet,norm_internet_log8,gdp,access_electricity,renew,happiness,unem,crime_rate,ineq,gov,maternal_mortality,pct_slums,homicide_rate,under_5yo_deaths,avg_life,trust_nat_gov
index,1.000000,-0.038943,-0.981314,-0.981314,-0.981314,-0.839410,-0.702414,0.106584,-0.794745,0.075947,0.585556,0.696259,-0.689827,0.699151,0.794389,0.347831,0.832113,-0.875046,-0.101684
year,-0.038943,1.000000,0.075983,0.075983,0.075983,0.045508,-0.118293,-0.036816,-0.016577,0.039234,-0.028039,-0.028277,0.014419,-0.045891,-0.045759,-0.089880,-0.043602,0.109277,-0.125135
internet,-0.981314,0.075983,1.000000,1.000000,1.000000,0.865360,0.596474,-0.053398,0.785829,-0.132024,-0.603122,-0.682461,0.716525,-0.593202,-0.757488,-0.362862,-0.738486,0.831346,0.140035
norm_internet,-0.981314,0.075983,1.000000,1.000000,1.000000,0.865360,0.596474,-0.053398,0.785829,-0.132024,-0.603122,-0.682461,0.716525,-0.593202,-0.757488,-0.362862,-0.738486,0.831346,0.140035
norm_internet_log8,-0.981314,0.075983,1.000000,1.000000,1.000000,0.865360,0.596474,-0.053398,0.785829,-0.132024,-0.603122,-0.682461,0.716525,-0.593202,-0.757488,-0.362862,-0.738486,0.831346,0.140035
gdp,-0.839410,0.045508,0.865360,0.865360,0.865360,1.000000,0.498353,-0.018153,0.790958,-0.206178,-0.526501,-0.609531,0.716033,-0.498310,-0.669467,-0.339864,-0.633776,0.765079,0.317733
access_electricity,-0.702414,-0.118293,0.596474,0.596474,0.596474,0.498353,1.000000,-0.341157,0.603337,0.101622,-0.386811,-0.647210,0.390696,-0.774998,-0.671941,-0.157465,-0.848341,0.753440,-0.098261
renew,0.106584,-0.036816,-0.053398,-0.053398,-0.053398,-0.018153,-0.341157,1.000000,0.101800,-0.016502,0.094307,0.313814,0.132005,0.183223,0.155724,0.186166,0.159474,-0.115632,0.143737
happiness,-0.794745,-0.016577,0.785829,0.785829,0.785829,0.790958,0.603337,0.101800,1.000000,-0.208783,-0.371687,-0.557718,0.724618,-0.520958,-0.655706,-0.086837,-0.653051,0.716250,0.174137
unem,0.075947,0.039234,-0.132024,-0.132024,-0.132024,-0.206178,0.101622,-0.016502,-0.208783,1.000000,0.217420,0.232614,-0.116768,-0.065881,-0.052960,0.168984,-0.046258,-0.058038,-0.306950
crime_rate,0.585556,-0.028039,-0.603122,-0.603122,-0.603122,-0.526501,-0.386811,0.094307,-0.371687,0.217420,1.000000,0.609586,-0.363182,0.459976,0.525167,0.537884,0.530749,-0.541306,-0.153787
ineq,0.696259,-0.028277,-0.682461,-0.682461,-0.682461,-0.609531,-0.647210,0.313814,-0.557718,0.232614,0.609586,1.000000,-0.322969,0.472116,0.627840,0.353388,0.642396,-0.643548,-0.117705
gov,-0.689827,0.014419,0.716525,0.716525,0.716525,0.716033,0.390696,0.132005,0.724618,-0.116768,-0.363182,-0.322969,1.000000,-0.384415,-0.479736,-0.235077,-0.501215,0.650870,0.293912
maternal_mortality,0.699151,-0.045891,-0.593202,-0.593202,-0.593202,-0.498310,-0.774998,0.183223,-0.520958,-0.065881,0.459976,0.472116,-0.384415,1.000000,0.644134,0.267923,0.922854,-0.801362,-0.074541
pct_slums,0.794389,-0.045759,-0.757488,-0.757488,-0.757488,-0.669467,-0.671941,0.155724,-0.655706,-0.052960,0.525167,0.627840,-0.479736,0.644134,1.000000,0.211070,0.755354,-0.720767,0.026261
homicide_rate,0.347831,-0.089880,-0.362862,-0.362862,-0.362862,-0.339864,-0.157465,0.186166,-0.086837,0.168984,0.537884,0.353388,-0.235077,0.267923,0.211070,1.000000,0.290074,-0.381067,-0.066806
under_5yo_deaths,0.832113,-0.043602,-0.738486,-0.738486,-0.738486,-0.633776,-0.848341,0.159474,-0.653051,-0.046258,0.530749,0.642396,-0.501215,0.922854,0.755354,0.290074,1.000000,-0.888056,-0.044200
avg_life,-0.875046,0.109277,0.831346,0.831346,0.831346,0.765079,0.753440,-0.115632,0.716250,-0.058038,-0.541306,-0.643548,0.650870,-0.801362,-0.720767,-0.381067,-0.888056,1.000000,0.156813
trust_nat_gov,-0.101684,-0.125135,0.140035,0.140035,0.140035,0.317733,-0.098261,0.143737,0.174137,-0.306950,-0.153787,-0.117705,0.293912,-0.074541,0.026261,-0.066806,-0.044200,0.156813,1.000000

In [400]:
eighteen.to_csv('eighteen_corr_0418.csv', index=False, header=True)

In [460]:
fifteen_forcor = eighteen[[ 'country', 'internet', 'gdp', 'access_electricity', 'renew', 'happiness',
       'unem', 'crime_rate', 'ineq', 'gov', 'maternal_mortality', 'pct_slums',
       'homicide_rate', 'under_5yo_deaths', 'avg_life', 'trust_nat_gov']]

In [418]:
subs = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\deaths-from-substance-disorders-who\deaths-from-substance-disorders-who.csv")

In [426]:
subs.columns = ['country', 'code', 'year', 'substance_abuse']

In [428]:
subs = subs.loc[subs['year'] >= 2020]

In [430]:
subs = subs.groupby('country').mean('substance_abuse')

In [446]:
neighbor = pd.read_csv(r"C:\Users\eabro\Downloads\share-people-trust-neighborhood\share-people-trust-neighborhood.csv")

In [448]:
neighbor.columns = ['country', 'code', 'year', 'neighbor_trust']

In [462]:
neighbor = neighbor.groupby('country').mean('neighbor_trust').reset_index()

In [470]:
sixteen_forcor = pd.merge(fifteen_forcor, neighbor, on = 'country', how = 'inner')

In [472]:
sixteen_forcor

,country,internet,gdp,access_electricity,renew,happiness,unem,crime_rate,ineq,gov,maternal_mortality,pct_slums,homicide_rate,under_5yo_deaths,avg_life,trust_nat_gov,year,neighbor_trust
0,Switzerland,46.962643,81101.41200,100.000000,61.217775,7.2636,4.5316,25.3,0.174857,9.110000,7.285693,0.000000,0.595970,0.420909,83.34,93.3,2020.0,87.7
1,France,46.323157,53983.22600,100.000000,21.977719,6.6480,7.7860,55.3,0.175082,7.680000,8.286672,0.000000,1.257723,0.397273,82.46,56.3,2020.0,78.7
2,Denmark,44.235214,69255.06000,100.000000,77.999250,7.5892,5.0548,26.3,0.110925,9.170000,5.453943,0.000000,0.976283,0.391818,81.12,79.3,2020.0,90.2
3,South Korea,43.393286,48497.68700,100.000000,6.228215,5.9654,3.3630,24.9,0.164216,8.213333,7.245308,4.350000,0.765223,0.357273,83.14,52.8,2020.0,75.0
4,Norway,43.303817,89001.77000,100.000000,98.489598,7.3272,3.8584,32.6,0.134010,9.640000,2.648812,0.000000,0.722262,0.293636,82.64,94.3,2020.0,93.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,Zambia,0.405331,3548.96052,37.845455,87.139390,3.8458,5.7344,46.4,0.633985,3.345000,178.852044,50.846667,5.747617,6.664545,62.31,47.1,2020.0,46.0
82,Ghana,0.351477,6610.83662,78.045455,37.831993,4.6388,3.1884,43.9,0.509502,5.178333,286.262974,35.170000,1.828209,6.594545,63.97,60.6,2020.0,55.2
83,Ethiopia,0.244803,2590.79340,41.481818,99.948256,4.0732,3.5788,50.8,0.364550,3.213333,427.519322,67.406667,8.631964,7.118182,64.92,78.1,2020.0,84.6
84,Uganda,0.082673,2713.66026,31.818182,97.653362,4.5008,3.2564,55.0,0.435286,3.450000,318.933335,58.271667,11.162656,7.431818,65.44,46.9,2020.0,47.4
85,Nigeria,0.040940,5535.29314,56.027273,22.960540,4.8116,4.6424,66.2,0.187159,3.810000,1108.942782,53.088333,27.672493,12.645455,52.82,23.1,2020.0,44.4

In [474]:
trust_sci = pd.read_csv(r"C:\Users\eabro\Downloads\share-people-trust-science\share-people-trust-science.csv")

In [482]:
trust_sci = trust_sci.groupby('Entity').mean('Trust science').reset_index()

In [486]:
trust_sci.columns = ['country', 'year', 'trust_sci']

In [510]:
seventeen_forcor = pd.merge(trust_sci, sixteen_forcor, on = 'country', how = 'inner')

In [512]:
seventeen_forcor = seventeen_forcor[['country', 'trust_sci', 'internet', 'gdp',
       'access_electricity', 'renew', 'happiness', 'unem', 'crime_rate',
       'ineq', 'gov', 'maternal_mortality', 'pct_slums', 'homicide_rate',
       'under_5yo_deaths', 'avg_life', 'trust_nat_gov',
       'neighbor_trust']]

In [496]:
seventeen_forcor.to_csv('seventeen_forcor_0419.csv', index=False, header=True)

In [498]:
seventeen_forcor.corr(numeric_only = True)

,trust_sci,internet,gdp,access_electricity,renew,happiness,unem,crime_rate,ineq,gov,maternal_mortality,pct_slums,homicide_rate,under_5yo_deaths,avg_life,trust_nat_gov,neighbor_trust
trust_sci,1.000000,0.652951,0.610235,0.452832,-0.081012,0.591740,-0.302116,-0.551481,-0.624204,0.463236,-0.542805,-0.499223,-0.390446,-0.613272,0.683706,0.427912,0.808499
internet,0.652951,1.000000,0.865360,0.596474,-0.053398,0.785829,-0.132024,-0.603122,-0.682461,0.716525,-0.593202,-0.757488,-0.362862,-0.738486,0.831346,0.140035,0.592674
gdp,0.610235,0.865360,1.000000,0.498353,-0.018153,0.790958,-0.206178,-0.526501,-0.609531,0.716033,-0.498310,-0.669467,-0.339864,-0.633776,0.765079,0.317733,0.643362
access_electricity,0.452832,0.596474,0.498353,1.000000,-0.341157,0.603337,0.101622,-0.386811,-0.647210,0.390696,-0.774998,-0.671941,-0.157465,-0.848341,0.753440,-0.098261,0.334709
renew,-0.081012,-0.053398,-0.018153,-0.341157,1.000000,0.101800,-0.016502,0.094307,0.313814,0.132005,0.183223,0.155724,0.186166,0.159474,-0.115632,0.143737,-0.107532
happiness,0.591740,0.785829,0.790958,0.603337,0.101800,1.000000,-0.208783,-0.371687,-0.557718,0.724618,-0.520958,-0.655706,-0.086837,-0.653051,0.716250,0.174137,0.440439
unem,-0.302116,-0.132024,-0.206178,0.101622,-0.016502,-0.208783,1.000000,0.217420,0.232614,-0.116768,-0.065881,-0.052960,0.168984,-0.046258,-0.058038,-0.306950,-0.269118
crime_rate,-0.551481,-0.603122,-0.526501,-0.386811,0.094307,-0.371687,0.217420,1.000000,0.609586,-0.363182,0.459976,0.525167,0.537884,0.530749,-0.541306,-0.153787,-0.628455
ineq,-0.624204,-0.682461,-0.609531,-0.647210,0.313814,-0.557718,0.232614,0.609586,1.000000,-0.322969,0.472116,0.627840,0.353388,0.642396,-0.643548,-0.117705,-0.648830
gov,0.463236,0.716525,0.716033,0.390696,0.132005,0.724618,-0.116768,-0.363182,-0.322969,1.000000,-0.384415,-0.479736,-0.235077,-0.501215,0.650870,0.293912,0.414364
maternal_mortality,-0.542805,-0.593202,-0.498310,-0.774998,0.183223,-0.520958,-0.065881,0.459976,0.472116,-0.384415,1.000000,0.644134,0.267923,0.922854,-0.801362,-0.074541,-0.422305
pct_slums,-0.499223,-0.757488,-0.669467,-0.671941,0.155724,-0.655706,-0.052960,0.525167,0.627840,-0.479736,0.644134,1.000000,0.211070,0.755354,-0.720767,0.026261,-0.428002
homicide_rate,-0.390446,-0.362862,-0.339864,-0.157465,0.186166,-0.086837,0.168984,0.537884,0.353388,-0.235077,0.267923,0.211070,1.000000,0.290074,-0.381067,-0.066806,-0.515934
under_5yo_deaths,-0.613272,-0.738486,-0.633776,-0.848341,0.159474,-0.653051,-0.046258,0.530749,0.642396,-0.501215,0.922854,0.755354,0.290074,1.000000,-0.888056,-0.044200,-0.515686
avg_life,0.683706,0.831346,0.765079,0.753440,-0.115632,0.716250,-0.058038,-0.541306,-0.643548,0.650870,-0.801362,-0.720767,-0.381067,-0.888056,1.000000,0.156813,0.576794
trust_nat_gov,0.427912,0.140035,0.317733,-0.098261,0.143737,0.174137,-0.306950,-0.153787,-0.117705,0.293912,-0.074541,0.026261,-0.066806,-0.044200,0.156813,1.000000,0.534107
neighbor_trust,0.808499,0.592674,0.643362,0.334709,-0.107532,0.440439,-0.269118,-0.628455,-0.648830,0.414364,-0.422305,-0.428002,-0.515934,-0.515686,0.576794,0.534107,1.000000

In [502]:
seventeen.to_csv('seventeen_0419.csv', index=False, header=True)

In [504]:
seventeen.corr(numeric_only = True)

,gdp,access_electricity,renew,happiness,unem,crime_rate,ineq,gov,maternal_mortality,pct_slums,homicide_rate,under_5yo_deaths,avg_life,trust_nat_gov
gdp,1.000000,0.498353,-0.018153,0.790958,-0.206178,-0.526501,-0.609531,0.716033,-0.498310,-0.669467,-0.339864,-0.633776,0.765079,0.317733
access_electricity,0.498353,1.000000,-0.341157,0.603337,0.101622,-0.386811,-0.647210,0.390696,-0.774998,-0.671941,-0.157465,-0.848341,0.753440,-0.098261
renew,-0.018153,-0.341157,1.000000,0.101800,-0.016502,0.094307,0.313814,0.132005,0.183223,0.155724,0.186166,0.159474,-0.115632,0.143737
happiness,0.790958,0.603337,0.101800,1.000000,-0.208783,-0.371687,-0.557718,0.724618,-0.520958,-0.655706,-0.086837,-0.653051,0.716250,0.174137
unem,-0.206178,0.101622,-0.016502,-0.208783,1.000000,0.217420,0.232614,-0.116768,-0.065881,-0.052960,0.168984,-0.046258,-0.058038,-0.306950
crime_rate,-0.526501,-0.386811,0.094307,-0.371687,0.217420,1.000000,0.609586,-0.363182,0.459976,0.525167,0.537884,0.530749,-0.541306,-0.153787
ineq,-0.609531,-0.647210,0.313814,-0.557718,0.232614,0.609586,1.000000,-0.322969,0.472116,0.627840,0.353388,0.642396,-0.643548,-0.117705
gov,0.716033,0.390696,0.132005,0.724618,-0.116768,-0.363182,-0.322969,1.000000,-0.384415,-0.479736,-0.235077,-0.501215,0.650870,0.293912
maternal_mortality,-0.498310,-0.774998,0.183223,-0.520958,-0.065881,0.459976,0.472116,-0.384415,1.000000,0.644134,0.267923,0.922854,-0.801362,-0.074541
pct_slums,-0.669467,-0.671941,0.155724,-0.655706,-0.052960,0.525167,0.627840,-0.479736,0.644134,1.000000,0.211070,0.755354,-0.720767,0.026261
homicide_rate,-0.339864,-0.157465,0.186166,-0.086837,0.168984,0.537884,0.353388,-0.235077,0.267923,0.211070,1.000000,0.290074,-0.381067,-0.066806
under_5yo_deaths,-0.633776,-0.848341,0.159474,-0.653051,-0.046258,0.530749,0.642396,-0.501215,0.922854,0.755354,0.290074,1.000000,-0.888056,-0.044200
avg_life,0.765079,0.753440,-0.115632,0.716250,-0.058038,-0.541306,-0.643548,0.650870,-0.801362,-0.720767,-0.381067,-0.888056,1.000000,0.156813
trust_nat_gov,0.317733,-0.098261,0.143737,0.174137,-0.306950,-0.153787,-0.117705,0.293912,-0.074541,0.026261,-0.066806,-0.044200,0.156813,1.000000

In [508]:
seventeen_forcor2 = pd.merge(trust_sci, seventeen, on = 'country', how = 'inner')

In [524]:
seventeen_forcor2 = pd.merge(urb, seventeen_forcor2,  on = 'country', how = 'inner')

In [530]:
seventeen_forcor2.to_csv('seventeen_0419_3pm.csv', index=False, header=True)

In [526]:
seventeen_forcor2

,country,urb_pop,year,trust_sci,gdp,access_electricity,renew,happiness,unem,crime_rate,ineq,gov,maternal_mortality,pct_slums,homicide_rate,under_5yo_deaths,avg_life,trust_nat_gov
0,Algeria,74.50850,2020.0,84.4,14766.34860,99.472727,0.902299,5.2546,12.8366,52.2,0.168092,2.560000,90.722890,19.773333,1.180476,2.439091,75.25,47.8
1,Argentina,92.28750,2020.0,81.4,26307.97260,99.818182,25.430562,6.1010,8.6046,64.2,0.231734,5.120000,42.252460,14.856667,6.163077,1.239091,76.18,43.9
2,Australia,86.42700,2020.0,85.8,57813.82400,100.000000,25.193850,7.0942,4.8198,47.1,0.184899,8.630000,5.115907,0.045000,1.007631,0.420909,83.06,69.5
3,Austria,59.13225,2020.0,89.5,64226.01160,100.000000,78.427917,7.0486,5.2910,29.3,0.150498,7.381667,5.644911,0.050000,0.744807,0.380909,81.58,73.4
4,Bangladesh,39.32675,2020.0,73.5,7485.03102,81.909091,1.456708,4.4398,5.3286,61.5,0.357639,5.486667,210.908847,52.883333,2.599225,4.147273,71.72,83.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,United Kingdom,84.27375,2020.0,92.8,53063.18500,100.000000,38.812949,6.8560,4.1640,47.4,0.168965,7.500000,8.855726,0.110000,1.065884,0.462727,81.02,47.7
82,United States,82.97975,2020.0,88.4,71120.37820,100.000000,19.830755,6.8542,4.8696,49.3,0.256936,6.608333,17.610667,0.165000,4.849181,0.699091,78.38,52.5
83,Uruguay,95.64425,2020.0,83.2,29864.07820,99.800000,93.082973,6.5342,8.9192,52.2,0.238460,8.810000,17.547967,3.170000,8.252915,0.990909,77.26,70.2
84,Zambia,45.47925,2020.0,64.7,3548.96052,37.845455,87.139390,3.8458,5.7344,46.4,0.633985,3.345000,178.852044,50.846667,5.747617,6.664545,62.31,47.1
85,Zimbabwe,32.36425,2020.0,68.0,3246.44688,43.727273,60.725946,3.2162,8.8760,60.9,0.513789,2.500000,447.897476,28.111667,5.738526,6.211818,60.25,69.0

In [528]:
press = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\data_grouped\Freedom_Liberties\press-freedom-index-rsf (1)\press-freedom-index-rsf.csv")

In [536]:
press.columns = ['country', 'code', 'year', 'free_press']

In [542]:
press = press.loc[press['year'] >=2018]

In [544]:
press = press.groupby('country').mean('free_press')

In [548]:
threepm_cor0419 = pd.merge(press, seventeen_forcor2, on = 'country', how = 'inner')

In [552]:
threepm_cor0419 = threepm_cor0419.drop('year_x', axis = 1)

In [554]:
threepm_cor0419

,country,free_press,urb_pop,year_y,trust_sci,gdp,access_electricity,renew,happiness,unem,crime_rate,ineq,gov,maternal_mortality,pct_slums,homicide_rate,under_5yo_deaths,avg_life,trust_nat_gov
0,Algeria,45.4150,74.50850,2020.0,84.4,14766.34860,99.472727,0.902299,5.2546,12.8366,52.2,0.168092,2.560000,90.722890,19.773333,1.180476,2.439091,75.25,47.8
1,Argentina,28.0300,92.28750,2020.0,81.4,26307.97260,99.818182,25.430562,6.1010,8.6046,64.2,0.231734,5.120000,42.252460,14.856667,6.163077,1.239091,76.18,43.9
2,Australia,18.0025,86.42700,2020.0,85.8,57813.82400,100.000000,25.193850,7.0942,4.8198,47.1,0.184899,8.630000,5.115907,0.045000,1.007631,0.420909,83.06,69.5
3,Austria,15.3725,59.13225,2020.0,89.5,64226.01160,100.000000,78.427917,7.0486,5.2910,29.3,0.150498,7.381667,5.644911,0.050000,0.744807,0.380909,81.58,73.4
4,Bangladesh,49.6100,39.32675,2020.0,73.5,7485.03102,81.909091,1.456708,4.4398,5.3286,61.5,0.357639,5.486667,210.908847,52.883333,2.599225,4.147273,71.72,83.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,United Kingdom,22.5000,84.27375,2020.0,92.8,53063.18500,100.000000,38.812949,6.8560,4.1640,47.4,0.168965,7.500000,8.855726,0.110000,1.065884,0.462727,81.02,47.7
82,United States,24.3000,82.97975,2020.0,88.4,71120.37820,100.000000,19.830755,6.8542,4.8696,49.3,0.256936,6.608333,17.610667,0.165000,4.849181,0.699091,78.38,52.5
83,Uruguay,15.9475,95.64425,2020.0,83.2,29864.07820,99.800000,93.082973,6.5342,8.9192,52.2,0.238460,8.810000,17.547967,3.170000,8.252915,0.990909,77.26,70.2
84,Zambia,36.7375,45.47925,2020.0,64.7,3548.96052,37.845455,87.139390,3.8458,5.7344,46.4,0.633985,3.345000,178.852044,50.846667,5.747617,6.664545,62.31,47.1
85,Zimbabwe,41.7075,32.36425,2020.0,68.0,3246.44688,43.727273,60.725946,3.2162,8.8760,60.9,0.513789,2.500000,447.897476,28.111667,5.738526,6.211818,60.25,69.0

In [556]:
pat = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\data_grouped\Education\patents.csv")

In [558]:
pat

,T29,Patents,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Region/Country/Area,NaN,Year,Series,Value,Footnotes,Source
1,1,"Total, all countries or areas",1985,Grants of patents (number),"397,580",NaN,World Intellectual Property Organization (WIPO...
2,1,"Total, all countries or areas",1995,Grants of patents (number),"429,800",NaN,World Intellectual Property Organization (WIPO...
3,1,"Total, all countries or areas",2005,Grants of patents (number),"632,500",NaN,World Intellectual Property Organization (WIPO...
4,1,"Total, all countries or areas",2010,Grants of patents (number),"915,200",NaN,World Intellectual Property Organization (WIPO...
...,...,...,...,...,...,...,...
1934,716,Zimbabwe,2005,Patents in force (number),194,NaN,World Intellectual Property Organization (WIPO...
1935,716,Zimbabwe,2010,Patents in force (number),310,NaN,World Intellectual Property Organization (WIPO...
1936,716,Zimbabwe,2020,Patents in force (number),473,NaN,World Intellectual Property Organization (WIPO...
1937,716,Zimbabwe,2021,Patents in force (number),477,NaN,World Intellectual Property Organization (WIPO...
1938,716,Zimbabwe,2022,Patents in force (number),513,NaN,World Intellectual Property Organization (WIPO...

In [560]:
electdem = pd.read_csv(r"C:\Users\eabro\Documents\NSS\Python\Projects\Utopia\data_grouped\Government\electoral-democracy-index.csv")

In [576]:
electdem.columns = ['country', 'year', 'elect_dem_i']

In [566]:
electdem = electdem.loc[electdem['year'] >= 2020]

In [574]:
electdem = electdem.groupby('country').mean('edi').reset_index()

In [578]:
threepm_cor0419 = pd.merge(electdem, threepm_cor0419, on = 'country', how = 'inner')

In [582]:
threepm_cor0419 = threepm_cor0419.drop('year', axis = 1)

In [584]:
threepm_cor0419.to_csv('corr_0419_3pm.csv', index=False, header=True)